### PR TITLE
Port to Gtk+3 and miscellaneous fixes

### LINKED ISSUE #2: MANIFEST is deprecated

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
Fixes #2 #3 #4 

- Removed MANIFEST
- Added .gitignore
- Updated license in activity.info to GPLv3+
- Ported to Gtk+3

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed.  Tested.

Your draw callback has a minor and harmless flaw.

- [ ] `_draw_cb` declares an argument `event` instead of `cr`,

https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Widget.html#Gtk.Widget.signals.draw

**Comment by yell0wfl4sh** [comment]
@quozl is this replacement required in ```_draw_cb``` only or will it be done in ```_resize_cb``` or more? I am a bit confused.

**Comment by quozl** [comment]
Hey, nice catch.  Thanks.  I only noticed `_draw_cb` because forgetting to change the method or argument names is a common mistake during GTK+ 2 to GTK+ 3 porting.  You're welcome to fix other method or argument names if you like.

**Comment by yell0wfl4sh** [comment]
I have made two change and squashed it in previous commit. while calling functions ```_draw_cb``` and ```_resize_cb``` , changed ```event``` argument to ```cr``` . I don't see anywhere else this change is required.

**Comment by quozl** [comment]
Reviewed.  To be perfect, `_resize_cb` should be renamed `_configure_event_cb`, and the argument was correctly `event` already, see

https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Widget.html#Gtk.Widget.signals.configure_event

I'd be fine with leaving `_resize_cb` method name unchanged though.

Sorry if it was not obvious.  We like callbacks to have some naming consistency with either their purpose (resize) or their source (configure event).  When it comes to arguments, they should be named according to the documentation, if practical.

On the other hand, Mancala activity is in a series of activities with pretty much the same code in different activities, so perhaps we shouldn't be too hasty.

**Comment by yell0wfl4sh** [comment]
Yes, I agree! If we follow the documentation strictly, we will have to rename 3-4 or more callback functions. but as you said, for sake of naming consistency with other activities, we can let it be. :)
you want me to change ```cr``` in ```_resize_cb``` back to ```event```?

**Comment by quozl** [comment]
yes.

**Pull request merged**
